# Site settings
title: Shengnan Zhang
subtitle_1: 'MS in Computer Science, NYU Courant'
subtitle_2: 'MS in Veterinary Medicine, Zhejiang Univ'
description: 'A multi-talented programmer who also plays well in veterinay and immunology research! (Believe or not, he is good at both writing code and butchering pigs..)'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: ''
resumeurl: 'https://drive.google.com/file/d/1BW6L3uboZd8uRDBjXbEP-9ZvAiUE-qq6/view?usp=sharing'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Shengnan Zhang'
  email: shengnanz@nyu.edu
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  synozhang
  linkedin_username:  shengnanz
  csdn_username: HLJs_Cookbook

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']


