# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: "/frontpage" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shengnan Zhang
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Master of Science in Computer Science, NYU Courant.
email: shengnanz@nyu.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
